"""
設定モジュール

共通定数、設定読み込みユーティリティ、リソース設定を提供。
"""

from src.config.resource_config import (
    GPUInfo,
    SystemResources,
    ResourceConfig,
    detect_system_resources,
    calculate_optimal_config,
    get_resource_config,
    init_resource_config,
    get_current_resource_config,
    print_resource_summary,
)

from src.config.constants import (
    # 定数
    TRADING_DAYS_PER_YEAR,
    TRADING_DAYS_PER_MONTH,
    TRADING_DAYS_PER_WEEK,
    DEFAULT_LOOKBACK_SHORT,
    DEFAULT_LOOKBACK_MEDIUM,
    DEFAULT_LOOKBACK_LONG,
    COV_HALFLIFE,
    DEFAULT_CHUNK_SIZE,
    STREAMING_CHUNK_SIZE,
    DEFAULT_CACHE_SIZE,
    SIGNAL_CACHE_SIZE,
    COVARIANCE_CACHE_SIZE,
    MOMENTUM_SHORT_WINDOW,
    MOMENTUM_MEDIUM_WINDOW,
    MOMENTUM_LONG_WINDOW,
    MEAN_REVERSION_WINDOW,
    MEAN_REVERSION_Z_THRESHOLD,
    MEAN_REVERSION_HALFLIFE,
    VOLATILITY_WINDOW,
    TARGET_VOLATILITY,
    RSI_PERIOD,
    RSI_OVERBOUGHT,
    RSI_OVERSOLD,
    BOLLINGER_WINDOW,
    BOLLINGER_NUM_STD,
    REGIME_LOOKBACK,
    SCORER_MIN_WEIGHT,
    SCORER_MAX_WEIGHT,
    LARGE_UNIVERSE_THRESHOLD,
    # 関数
    get_constant,
    get_nested_config,
    get_trading_days,
    get_lookback,
    get_signal_param,
    get_meta_param,
    reload_config,
)

__all__ = [
    # リソース設定
    "GPUInfo",
    "SystemResources",
    "ResourceConfig",
    "detect_system_resources",
    "calculate_optimal_config",
    "get_resource_config",
    "init_resource_config",
    "get_current_resource_config",
    "print_resource_summary",
    # 定数
    "TRADING_DAYS_PER_YEAR",
    "TRADING_DAYS_PER_MONTH",
    "TRADING_DAYS_PER_WEEK",
    "DEFAULT_LOOKBACK_SHORT",
    "DEFAULT_LOOKBACK_MEDIUM",
    "DEFAULT_LOOKBACK_LONG",
    "COV_HALFLIFE",
    "DEFAULT_CHUNK_SIZE",
    "STREAMING_CHUNK_SIZE",
    "DEFAULT_CACHE_SIZE",
    "SIGNAL_CACHE_SIZE",
    "COVARIANCE_CACHE_SIZE",
    "MOMENTUM_SHORT_WINDOW",
    "MOMENTUM_MEDIUM_WINDOW",
    "MOMENTUM_LONG_WINDOW",
    "MEAN_REVERSION_WINDOW",
    "MEAN_REVERSION_Z_THRESHOLD",
    "MEAN_REVERSION_HALFLIFE",
    "VOLATILITY_WINDOW",
    "TARGET_VOLATILITY",
    "RSI_PERIOD",
    "RSI_OVERBOUGHT",
    "RSI_OVERSOLD",
    "BOLLINGER_WINDOW",
    "BOLLINGER_NUM_STD",
    "REGIME_LOOKBACK",
    "SCORER_MIN_WEIGHT",
    "SCORER_MAX_WEIGHT",
    "LARGE_UNIVERSE_THRESHOLD",
    # 関数
    "get_constant",
    "get_nested_config",
    "get_trading_days",
    "get_lookback",
    "get_signal_param",
    "get_meta_param",
    "reload_config",
]
